name: CloudHw CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Spring Boot Application 빌드 후 Docker Hub에 Push
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Java 17 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 2. gradlew 실행 권한 부여
      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      # 3. Gradle 의존성 캐싱
      - name: Dependency Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key:
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys:
            ${{ runner.os }}-gradle-

      # 4. application.yml 생성
      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "application.yml 생성 시작..."
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      # 5. Gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      # 6. Spring Boot Application 빌드
      - name: Build with Gradle
        run: |
          ./gradlew clean bootJar
          ls -l build/libs/

      # 7. Docker 이미지 빌드
      - name: Docker image build
        run: |
          docker build \
          --label commit=${{ github.sha }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/cloudhw_cicd_action:${{ github.sha }} \
          .

      # 8. 이미지 태깅
      - name: Tag Latest Image
        run : |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cloudhw_cicd_action:${{ github.sha }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/cloudhw_cicd_action:latest

      # 9. DockerHub 로그인
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 10. Docker Hub에 이미지 Push
      - name: Docker Hub push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloudhw_cicd_action:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloudhw_cicd_action:latest
